# Generated by Django 4.2.10 on 2024-02-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
