# Generated by Django 5.0.2 on 2024-05-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_alter_item_category_alter_item_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
