# Generated by Django 4.2.10 on 2024-02-16 21:10

from django.db import migrations, models
import warehouses.models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dimensions',
            field=models.JSONField(null=True, validators=[warehouses.models.validate_dimensions]),
        ),
    ]
