# Generated by Django 4.2.10 on 2024-02-16 21:18

from django.db import migrations, models
import warehouses.models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0003_item_dimensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='dimensions',
            field=models.JSONField(blank=True, null=True, validators=[warehouses.models.validate_dimensions]),
        ),
        migrations.AlterField(
            model_name='item',
            name='state',
            field=models.CharField(choices=[], max_length=100),
        ),
    ]
