# Generated by Django 4.2.10 on 2024-02-19 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouses', '0004_alter_item_category_alter_item_dimensions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('', 'Select Category')], max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='state',
            field=models.CharField(choices=[('', 'Select State')], max_length=100),
        ),
    ]
