# Generated by Django 5.0.2 on 2024-02-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0008_employeeworkinghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeworkinghours',
            name='week_day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday')]),
        ),
    ]
