# Generated by Django 5.0.2 on 2024-02-29 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0010_itemedit'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ItemOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouses.employee')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouses.item')),
            ],
        ),
    ]
