# Generated by Django 5.0.2 on 2024-02-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0011_item_shipped_itemorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemorder',
            name='item',
        ),
        migrations.AddField(
            model_name='itemorder',
            name='item',
            field=models.ManyToManyField(related_name='ordered_items', to='warehouses.item'),
        ),
    ]
