# Generated by Django 5.0.2 on 2024-02-29 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0012_remove_itemorder_item_itemorder_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Employee',
            new_name='employee',
        ),
        migrations.AddField(
            model_name='contact',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 29, 17, 59, 56, 421274, tzinfo=datetime.timezone.utc)),
        ),
    ]
