# Generated by Django 5.0.2 on 2024-02-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0013_rename_employee_contact_employee_contact_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
