# Generated by Django 5.0.2 on 2024-02-29 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0015_communication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Communication',
        ),
    ]
