# Generated by Django 5.0.2 on 2024-02-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0016_delete_communication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='communications',
            field=models.ManyToManyField(related_name='contacts', to='warehouses.communication'),
        ),
    ]
